# Generated by Django 5.2.1 on 2025-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='permission',
            field=models.CharField(choices=[('edit', 'Pode Editar'), ('view', 'Pode Visualizar')], max_length=10),
        ),
    ]
